#!/usr/bin/env bash
# Bring the whole stack up in one tmux session, one window per process:
#
#   vllm        Qwen3.6-27B-FP8 on $MODEL_PORT - splits the orders AND does the OCR
#   api-tunnel  cloudflared: api.jaypokale.me    -> $MODEL_PORT
#   web         static file server for this repo -> $WEB_PORT
#   web-tunnel  cloudflared: remarks.jaypokale.me -> $WEB_PORT
#
# Run this ON THE GPU NODE (the GPU node). vllm needs CUDA; the login node has no
# GPU and the model window will die there. Home is shared, so the files are the
# same either way.
#
#   ./deploy/start_all.sh              # everything
#   SKIP_VLLM=1 ./deploy/start_all.sh  # model already up elsewhere: web bits only
#   ./deploy/start_all.sh --check      # verify prerequisites, start nothing
#
# NOTE: the remarks tunnel id is shared with the iit-hyderabad deployment. Running
# both at once makes Cloudflare split remarks.jaypokale.me between the two hosts,
# so stop the tunnel there before starting it here.
#
set -uo pipefail

CHECK_ONLY=0
[ "${1:-}" = "--check" ] && CHECK_ONLY=1

SESSION=${SESSION:-gst-para}
APP_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
BASE=${BASE:-$(dirname "$APP_DIR")}

MODEL_PORT=${MODEL_PORT:-8033}
WEB_PORT=${WEB_PORT:-8013}
GPU=${GPU:-3}
MODEL=${MODEL:-Qwen/Qwen3.6-27B-FP8}

ENV_DIR=$BASE/vllm_env2
CF_DIR=$BASE/cloudflared-model
LOGDIR=$BASE/logs
KEYFILE=$BASE/.vllm_api_key
API_CONFIG=$CF_DIR/config-api.yml
REMARKS_CREDS=$CF_DIR/remarks.json
# written below with paths correct for THIS machine - the checked-in
# config-remarks.yml points at the other server's /workspace/... layout
REMARKS_CONFIG=$CF_DIR/config-remarks.local.yml

mkdir -p "$LOGDIR"

die(){ echo "ERROR: $*" >&2; exit 1; }

# nvidia-smi is installed on the login node too and exits 0 while reporting it
# cannot reach the driver, so ask it to actually list a GPU.
have_gpu(){ nvidia-smi -L 2>/dev/null | grep -q '^GPU 0'; }

command -v tmux >/dev/null || die "tmux not found"
command -v python3 >/dev/null || die "python3 not found"

CF=$(command -v cloudflared || true)
[ -z "$CF" ] && [ -x "$HOME/bin/cloudflared" ] && CF=$HOME/bin/cloudflared
[ -z "$CF" ] && [ -f "$BASE/cloudflared" ] && [ -x "$BASE/cloudflared" ] && CF=$BASE/cloudflared
[ -n "$CF" ] || die "cloudflared not found (looked in PATH, ~/bin, $BASE)"

[ -f "$API_CONFIG" ]    || die "missing $API_CONFIG"
[ -f "$REMARKS_CREDS" ] || die "missing $REMARKS_CREDS - create the remarks tunnel first"
[ -f "$KEYFILE" ]       || die "missing $KEYFILE - start_qwen.sh writes it; the key is never kept in this repo"

# the tunnel id must come from the credentials file, not a hand-edited config
TUNNEL_ID=$(python3 -c "import json,sys;print(json.load(open(sys.argv[1]))['TunnelID'])" "$REMARKS_CREDS") \
  || die "could not read TunnelID from $REMARKS_CREDS"

cat > "$REMARKS_CONFIG" <<EOF
# generated by deploy/start_all.sh - edit the script, not this file
tunnel: $TUNNEL_ID
credentials-file: $REMARKS_CREDS
ingress:
  - hostname: remarks.jaypokale.me
    service: http://localhost:$WEB_PORT
  - service: http_status:404
EOF

if [ "$CHECK_ONLY" = "1" ]; then
  echo "app dir     : $APP_DIR"
  echo "cloudflared : $CF"
  echo "api config  : $API_CONFIG"
  echo "remarks cfg : $REMARKS_CONFIG (generated, tunnel $TUNNEL_ID)"
  echo "gpu         : $(have_gpu && echo present || echo 'ABSENT - login node, vllm would fail')"
  curl -sf -m 3 -o /dev/null "http://localhost:$MODEL_PORT/v1/models" -H "Authorization: Bearer $(cat "$KEYFILE")" \
    && echo "model       : already serving on $MODEL_PORT" \
    || echo "model       : not serving on $MODEL_PORT (would be started)"
  echo "checks passed - nothing started"
  exit 0
fi

# --- is the model already serving? then leave it alone ---
SKIP_VLLM=${SKIP_VLLM:-0}
if [ "$SKIP_VLLM" != "1" ] && curl -sf -m 3 -o /dev/null "http://localhost:$MODEL_PORT/v1/models" \
     -H "Authorization: Bearer $(cat "$KEYFILE")"; then
  echo "vllm already answering on $MODEL_PORT - not starting a second copy"
  SKIP_VLLM=1
fi
if [ "$SKIP_VLLM" != "1" ] && ! have_gpu; then
  echo "WARNING: no nvidia-smi here - this looks like the login node, and vllm will fail."
  echo "         Run this on the GPU node, or use SKIP_VLLM=1 for the web side only."
fi

# --- clear only what we own: our session, our two ports, our two tunnels ---
tmux kill-session -t "$SESSION" 2>/dev/null
[ "$SKIP_VLLM" = "1" ] || fuser -k "$MODEL_PORT/tcp" 2>/dev/null
fuser -k "$WEB_PORT/tcp" 2>/dev/null
pkill -u "$USER" -f "$API_CONFIG" 2>/dev/null
pkill -u "$USER" -f "$REMARKS_CONFIG" 2>/dev/null
sleep 2

tmux new-session -d -s "$SESSION" -n web
tmux send-keys -t "$SESSION":web \
  "cd '$APP_DIR' && python3 -m http.server $WEB_PORT --bind 127.0.0.1 2>&1 | tee $LOGDIR/web_${WEB_PORT}.log" C-m

tmux new-window -t "$SESSION" -n web-tunnel
tmux send-keys -t "$SESSION":web-tunnel \
  "$CF tunnel --config '$REMARKS_CONFIG' --protocol http2 --no-autoupdate run 2>&1 | tee $LOGDIR/cloudflared_remarks.log" C-m

if [ "$SKIP_VLLM" != "1" ]; then
  tmux new-window -t "$SESSION" -n vllm
  tmux send-keys -t "$SESSION":vllm "
source /export/software/miniconda/etc/profile.d/conda.sh
conda activate $ENV_DIR
export PYTHONNOUSERSITE=1
export CUDA_VISIBLE_DEVICES=$GPU
export HF_HOME=$BASE/hf_cache
export HF_HUB_OFFLINE=1
export VLLM_USE_DEEP_GEMM=0
unset VLLM_NUM_GPU_BLOCKS_OVERRIDE VLLM_USE_V1
vllm serve $MODEL \
  --port $MODEL_PORT \
  --gpu-memory-utilization 0.85 \
  --max-num-seqs 64 \
  --max-model-len 131072 \
  --limit-mm-per-prompt '{\"image\": 4}' \
  --reasoning-parser qwen3 \
  --api-key '\$(cat $KEYFILE)' \
  2>&1 | tee $LOGDIR/vllm_${MODEL_PORT}.log
" C-m
fi

# Always start the api tunnel, even when vllm was already running: the tunnel is a
# separate process and it is usually the half that has died (Cloudflare 1033 /
# HTTP 530 on api.jaypokale.me while vllm is still happily serving on localhost).
tmux new-window -t "$SESSION" -n api-tunnel
tmux send-keys -t "$SESSION":api-tunnel \
  "$CF tunnel --config '$API_CONFIG' --protocol http2 --no-autoupdate run 2>&1 | tee $LOGDIR/cloudflared_api.log" C-m

cat <<EOF

Session '$SESSION' is up.
  windows : $(tmux list-windows -t "$SESSION" -F '#W' | tr '\n' ' ')
  app     : https://remarks.jaypokale.me   (local http://127.0.0.1:$WEB_PORT)
  model   : https://api.jaypokale.me       (local http://127.0.0.1:$MODEL_PORT)
  logs    : $LOGDIR

  attach  : tmux attach -t $SESSION      (switch windows with Ctrl-b n / Ctrl-b <number>)
  stop    : tmux kill-session -t $SESSION

The model takes a couple of minutes to load - the page will report "The model
server did not answer" until the vllm window says it is serving.
EOF

tmux select-window -t "$SESSION":web
[ -t 1 ] && exec tmux attach -t "$SESSION"
exit 0
